### ISSUE TITLE
Thou hath not written thy interpreter in olde English

### ISSUE THREAD

**Issue by easyaspi314** [sampersand/squire#1]
Whilst thy programming language useth olde english, thy interpreter useth strange and unusual words such as "opcode", "expression", and "function".

**Comment by sampersand** [comment]
Yet another one of those legacy "Wontfix" things—i originally made it a "normal" langauge (aka a cheap ripoff of javascript/go/somethin), and had the stuff named like that. When I switched over, I never renamed. 

New stuff's named with fun thigns though, eg `codex`.
